import json
import pandas as pd
from pandas import DataFrame
from app.helper.paths import FRAMEWORK_ROOT
import os


def get_name_and_description(framework: str, group: str, uri: str) -> dict:
    """
    Extracts and returns a name and a description of a given entry of a specified framework.

    :param framework: The framework the entry is from.
    :type framework: str
    :param group: The group the framework belongs to (e.g. educationalAlignment).
    :type group: str
    :param uri: The URI of the entity as an unambiguous identifier.
    :type uri: str
    :return: The name and the description of the entry.
    :rtype: dict
    """

    data = get_full_framework(group, framework)

    return {
        "name": data[data["uri"] == uri]["name"].item(),
        "description": data[data["uri"] == uri]["description"].item()
    }


def get_full_framework(group: str, framework: str) -> DataFrame:
    """
    Returns the specified framework as a pandas DataFrame.

    :param group: The group the framework belongs to.
    :type group: str
    :param framework: The framework to be returned.
    :type framework: str
    :return: The complete framework.
    :rtype: pandas.DataFrame
    """

    path = (
        FRAMEWORK_ROOT /
        group /
        framework
    )

    file = [file for file in os.listdir(path) if file[-4:] == ".csv"][0]

    path = (
            path /
            file
    )

    return pd.read_csv(path, dtype=str)


def get_uri_by_name(name: str, group: str, framework: str) -> str:
    """
    Return the URI of a framework entry identified by its name. The framework
    is searched by the name and only the entry with the highest level is returned
    in case that thee are several entries with the same name.

    :param name: The name of the entry.
    :type name: str
    :param group: The attribute the entry belongs to.
    :type group: str
    :param framework: The framework the entry belongs to.
    :type framework: str
    :return: The URI of the entry.
    :rtype: str
    """
    data = get_full_framework(group, framework)
    data = data[data["name"] == name]
    max_level = data["level"].max()

    return data[data["level"] == max_level]["uri"].item()


def get_ed_level_uri_by_name(name: str, framework: str) -> str:
    """
    Return the URI of an educationalLevel identified by its name. Currently, only the
    DigComp is supported as a framework. The name is generated by extending the term
    "Level" with the provided name before conducting the search in the framework.

    :param name: The name of the level as the short code e.g. "2".
    :type name: str
    :param framework: The educationalLevel framework the entry belongs.
    :type framework: str
    :return: The URI of the entry in the defined framework.
    :rtype: str
    """
    data = get_full_framework("educationalLevel", framework)
    name = f"Level {name}"
    return data[data["name"].str.contains(name)]["uri"].item()


def find_top_level_entries(group: str, framework: str) -> DataFrame:
    """
    Find all level 1 entries of a given framework. This is needed to start the
    dropdown menu of the frameworks on the user interface.

    :param group: The attribute the entries belong to.
    :type group: str
    :param framework: The framework the entries belong to.
    :type framework: str
    :return: A DataFrame containing all level 1 entries of a given framework.
    :rtype: DataFrame
    """
    data = get_full_framework(group, framework)

    return data[data["level"] == "1"]


def find_sub_entries(group: str, framework: str, uri: str) -> DataFrame:
    """
    Find all sub-entries to a given entry. This is important to build the dropdown
    menu for the user interface dynamically.

    :param group: The attribute the entries belong to.
    :type group: str
    :param framework: The framework the entries belong to.
    :type framework: str
    :param uri: The URI of the entry as unique identifier within the framework.
    :return: A DataFrame with all sub-entries for a given entry.
    :rtype: DataFrame
    """
    data = get_full_framework(group, framework)
    sub_entries = json.loads(data[data["uri"] == uri]["narrowerconcept"].item().replace("'", '"'))  # TODO: eval instead?

    return data[data["uri"].isin(sub_entries)]
